version: 2.1

references:
  workspace_root: &workspace_root
      ~/sdk

  container_config: &container_config
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    working_directory: *workspace_root

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  general_cache_key: &general_cache_key
    key: cache-{{ checksum "build.gradle" }}
    paths:
      - ~/.gradle

jobs:
  test:
    <<: *container_config
    steps:
      - *attach_workspace
      - checkout
      - restore_cache:
          <<: *general_cache_key

      - run: ./.circleci/host-hotfix.sh
      - run: ./gradlew build -x check --no-daemon --stacktrace --console=plain -PdisablePreDex
      - run: ./gradlew check jacocoTestReport --no-daemon --stacktrace --console=plain -PdisablePreDex

      - save_cache:
          <<: *general_cache_key

      - run: bash <(curl -s https://codecov.io/bash)

      - store_test_results:
          path: ./build/test-results
      - store_artifacts:
          path: ./build/reports/jacoco/test
      - store_artifacts:
          path: ./build/reports/tests/test
      - store_artifacts:
          path: ./build/libs/sdk-0.20.5.jar
  deploy:
    <<: *container_config
    steps:
      - *attach_workspace
      - checkout
      - restore_cache:
          <<: *general_cache_key

      - run: ./gradlew bintrayUpload --no-daemon --stacktrace --console=plain -PdisablePreDex

workflows:
  version: 2

  test-and-deploy:
    jobs:
    - test
    - deploy:
        requires:
          - test
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /\d+\.\d+\.\d+/
